name: Publish

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  SQLX_OFFLINE: "true"

jobs:
  upload-assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@631a55b12751854ce901bb631d5902ceb48146f7 # stable
        with:
          targets: x86_64-unknown-linux-musl

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2

      - name: Install musl tools
        run: sudo apt-get install -y musl-tools

      - name: Upload binary
        uses: taiki-e/upload-rust-binary-action@f391289bcff6a7f36b6301c0a74199657bbb4561 # v1
        with:
          bin: reader-sync
          target: x86_64-unknown-linux-musl
          archive: $bin-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS: "-C target-cpu=native"
